# requirements

install.packages("ggplot2")
install.packages("dplyr")
install.packages("readxl")
# install.packages("RCurl")
install.packages("httr")
install.packages("KoNLP")
install.packages("igraph")
install.packages("arules")
# install.packages("KoNLP")
install.packages("https://cran.rstudio.com/bin/windows/contrib/3.4/KoNLP_0.80.1.zip", repos = NULL)
install.packages("KoNLP", repos = "https://forkonlp.r-universe.dev", INSTALL_opts = c("–no-multiarch") )
install.packages("Sejong")
install.packages("hash")
install.packages("tau")
install.packages("RSQLite")
install.packages("devtools")
# install.packages("googleLanguageR")
# require(devtools)
# devtools::install_github("bmschmidt/wordVectors")
# install.packages("wordVectors")
# install.packages("readr")
install.packages("topicmodels")
install.packages("SnowballC")
install.packages("lda")
install.packages("ldatuning")
# devtools::install_github("cpsievert/LDAvisData", force=T)
install.packages("LDAvis")
install.packages('servr')
